/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.CorridasJpaController;
import control.LugaresJpaController;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Corridas;
import modelo.Lugares;
import modelo.ModeloTablaCorridas;

/**
 *
 * @author fernando
 */
public class Sistema extends javax.swing.JFrame {

    EntityManagerFactory emf;
    Corridas corr;
    Lugares lugares;
    LugaresJpaController cl;
    CorridasJpaController co;
    String estado = "";
    ModeloTablaCorridas cor;

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        DesactivarPasillo();
        AgregarOrigen();
        Calendario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        AutobusesPUEntityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AutobusesPU").createEntityManager();
        corridasQuery = java.beans.Beans.isDesignTime() ? null : AutobusesPUEntityManager0.createQuery("SELECT c FROM Corridas c");
        corridasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : corridasQuery.getResultList();
        corridasQuery1 = java.beans.Beans.isDesignTime() ? null : AutobusesPUEntityManager0.createQuery("SELECT c FROM Corridas c");
        corridasList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : corridasQuery1.getResultList();
        corridasQuery2 = java.beans.Beans.isDesignTime() ? null : AutobusesPUEntityManager0.createQuery("SELECT c FROM Corridas c");
        corridasList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : corridasQuery2.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        origen = new javax.swing.JComboBox();
        destino = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        calendario1 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        corridas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        a32 = new javax.swing.JButton();
        a7 = new javax.swing.JButton();
        a11 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        a8 = new javax.swing.JButton();
        a12 = new javax.swing.JButton();
        a4 = new javax.swing.JButton();
        a16 = new javax.swing.JButton();
        a15 = new javax.swing.JButton();
        a19 = new javax.swing.JButton();
        a20 = new javax.swing.JButton();
        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        a10 = new javax.swing.JButton();
        a6 = new javax.swing.JButton();
        a5 = new javax.swing.JButton();
        a9 = new javax.swing.JButton();
        a17 = new javax.swing.JButton();
        a13 = new javax.swing.JButton();
        a14 = new javax.swing.JButton();
        a18 = new javax.swing.JButton();
        a21 = new javax.swing.JButton();
        a22 = new javax.swing.JButton();
        a23 = new javax.swing.JButton();
        a24 = new javax.swing.JButton();
        a25 = new javax.swing.JButton();
        a26 = new javax.swing.JButton();
        a27 = new javax.swing.JButton();
        a28 = new javax.swing.JButton();
        a30 = new javax.swing.JButton();
        a31 = new javax.swing.JButton();
        p5 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        a29 = new javax.swing.JButton();
        a33 = new javax.swing.JButton();
        a34 = new javax.swing.JButton();
        a37 = new javax.swing.JButton();
        a38 = new javax.swing.JButton();
        a35 = new javax.swing.JButton();
        a36 = new javax.swing.JButton();
        a39 = new javax.swing.JButton();
        a40 = new javax.swing.JButton();
        p2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Origen ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 226, 44));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Busqueda de Corrida");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 226, 44));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Destino");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 226, 44));

        origen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                origenMouseClicked(evt);
            }
        });
        jPanel3.add(origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 100, -1));

        jPanel3.add(destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 90, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Fecha");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 100, 44));

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));
        jPanel3.add(calendario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 220, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 80, -1));

        jTabbedPane1.addTab("Inicio", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, corridasList2, corridas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numCorridas}"));
        columnBinding.setColumnName("Num Corridas");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${origen}"));
        columnBinding.setColumnName("Origen");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${destino}"));
        columnBinding.setColumnName("Destino");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hora}"));
        columnBinding.setColumnName("Hora");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${claseAutobus}"));
        columnBinding.setColumnName("Clase Autobus");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precio}"));
        columnBinding.setColumnName("Precio");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lugares}"));
        columnBinding.setColumnName("Lugares");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        corridas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corridasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(corridas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 6, 714, 330));

        jButton2.setText("Aceptar Seleccion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jTabbedPane1.addTab("Corridas", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a32.setText("32");
        a32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a32ActionPerformed(evt);
            }
        });
        jPanel4.add(a32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 50, -1));

        a7.setText("7");
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });
        jPanel4.add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 50, -1));

        a11.setText("11");
        a11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a11ActionPerformed(evt);
            }
        });
        jPanel4.add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 50, -1));

        a3.setText("3");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        jPanel4.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 50, -1));

        a8.setText("8");
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });
        jPanel4.add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 50, -1));

        a12.setText("12");
        a12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a12ActionPerformed(evt);
            }
        });
        jPanel4.add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 50, -1));

        a4.setText("4");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        jPanel4.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 50, -1));

        a16.setText("16");
        a16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a16ActionPerformed(evt);
            }
        });
        jPanel4.add(a16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 50, -1));

        a15.setText("15");
        a15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a15ActionPerformed(evt);
            }
        });
        jPanel4.add(a15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 50, -1));

        a19.setText("19");
        a19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a19ActionPerformed(evt);
            }
        });
        jPanel4.add(a19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 50, -1));

        a20.setText("20");
        a20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a20ActionPerformed(evt);
            }
        });
        jPanel4.add(a20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 50, -1));

        a1.setText("1");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jPanel4.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, -1));

        a2.setText("2");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jPanel4.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, -1));

        a10.setText("10");
        a10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a10ActionPerformed(evt);
            }
        });
        jPanel4.add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 50, -1));

        a6.setText("6");
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        jPanel4.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 50, -1));

        a5.setText("5");
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        jPanel4.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 50, -1));

        a9.setText("9");
        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });
        jPanel4.add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 50, -1));

        a17.setText("17");
        a17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a17ActionPerformed(evt);
            }
        });
        jPanel4.add(a17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 50, -1));

        a13.setText("13");
        a13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a13ActionPerformed(evt);
            }
        });
        jPanel4.add(a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 50, -1));

        a14.setText("14");
        a14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a14ActionPerformed(evt);
            }
        });
        jPanel4.add(a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 50, -1));

        a18.setText("18");
        a18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a18ActionPerformed(evt);
            }
        });
        jPanel4.add(a18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 50, -1));

        a21.setText("21");
        a21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a21ActionPerformed(evt);
            }
        });
        jPanel4.add(a21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 50, -1));

        a22.setText("22");
        a22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a22ActionPerformed(evt);
            }
        });
        jPanel4.add(a22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 50, -1));

        a23.setText("23");
        a23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a23ActionPerformed(evt);
            }
        });
        jPanel4.add(a23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 50, -1));

        a24.setText("24");
        a24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a24ActionPerformed(evt);
            }
        });
        jPanel4.add(a24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 50, -1));

        a25.setText("25");
        a25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a25ActionPerformed(evt);
            }
        });
        jPanel4.add(a25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 50, -1));

        a26.setText("26");
        a26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a26ActionPerformed(evt);
            }
        });
        jPanel4.add(a26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 50, -1));

        a27.setText("27");
        a27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a27ActionPerformed(evt);
            }
        });
        jPanel4.add(a27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 50, -1));

        a28.setText("28");
        a28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a28ActionPerformed(evt);
            }
        });
        jPanel4.add(a28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 50, -1));

        a30.setText("30");
        a30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a30ActionPerformed(evt);
            }
        });
        jPanel4.add(a30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 50, -1));

        a31.setText("31");
        a31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a31ActionPerformed(evt);
            }
        });
        jPanel4.add(a31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 50, -1));

        p5.setText("Pasillo");
        jPanel4.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        p1.setText("Pasillo");
        jPanel4.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        p3.setText("Pasillo");
        jPanel4.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        p4.setText("Pasillo");
        jPanel4.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        a29.setText("29");
        a29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a29ActionPerformed(evt);
            }
        });
        jPanel4.add(a29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 50, -1));

        a33.setText("33");
        a33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a33ActionPerformed(evt);
            }
        });
        jPanel4.add(a33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 50, -1));

        a34.setText("34");
        a34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a34ActionPerformed(evt);
            }
        });
        jPanel4.add(a34, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 50, -1));

        a37.setText("37");
        a37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a37ActionPerformed(evt);
            }
        });
        jPanel4.add(a37, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 50, -1));

        a38.setText("38");
        a38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a38ActionPerformed(evt);
            }
        });
        jPanel4.add(a38, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 50, -1));

        a35.setText("35");
        a35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a35ActionPerformed(evt);
            }
        });
        jPanel4.add(a35, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 50, -1));

        a36.setText("36");
        a36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a36ActionPerformed(evt);
            }
        });
        jPanel4.add(a36, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 50, -1));

        a39.setText("39");
        a39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a39ActionPerformed(evt);
            }
        });
        jPanel4.add(a39, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 50, -1));

        a40.setText("40");
        a40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a40ActionPerformed(evt);
            }
        });
        jPanel4.add(a40, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 50, -1));

        p2.setText("Pasillo");
        jPanel4.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jButton3.setText("Continuar");
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 90, 30));

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jTabbedPane1.addTab("Reserva", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Asignar pasaje", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Boleto", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cancelar", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void DesactivarPasillo() {
        p1.setEnabled(false);
        p2.setEnabled(false);
        p3.setEnabled(false);
        p4.setEnabled(false);
        p5.setEnabled(false);
    }

    private void ConexionLocal() {
        emf = Persistence.createEntityManagerFactory("AutobusesPU");
        cl = new LugaresJpaController(emf);
        co = new CorridasJpaController(emf);
    }

    private void AgregarOrigen() {
        ConexionLocal();
        List<Lugares> listLugares;
        listLugares = cl.findLugaresEntities();
        for (int i = 0; i < listLugares.size(); i++) {
            origen.addItem(listLugares.get(i).getLugar());
        }

    }

    public void Calendario() {
        Date date = new Date();
        calendario1.setMinSelectableDate(date);

    }
    
  

    public void BuscarC() {
        ConexionLocal();
        String formato = "yyyy/MM/dd";
        Date date = calendario1.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        String o = origen.getSelectedItem().toString();
        String d = destino.getSelectedItem().toString();
        List<Corridas> listCorridas;
        listCorridas = co.findCorridasEntities();
        for (int i = 0; i < listCorridas.size(); i++) {
            if(listCorridas.get(i).getOrigen().toString().equals(o) &&
               listCorridas.get(i).getDestino().toString().equals(d) && 
                    sdf.format(listCorridas.get(i).getFecha()).equals(sdf.format(date))) {
                    System.out.println("funcionó");
            }
            
        }
        
        
      //  fechaTxt.setText(sdf.format(date));
    }
    private void Activar(){
        a1.setEnabled(true);
        a2.setEnabled(true);
        a3.setEnabled(true);
        a4.setEnabled(true);
        a5.setEnabled(true);
        a6.setEnabled(true);
        a7.setEnabled(true);
        a8.setEnabled(true);
        a9.setEnabled(true);
        a10.setEnabled(true);
        a11.setEnabled(true);
        a12.setEnabled(true);
        a13.setEnabled(true);
        a14.setEnabled(true);
        a15.setEnabled(true);
        a16.setEnabled(true);
        a17.setEnabled(true);
        a18.setEnabled(true);
        a19.setEnabled(true);
        a20.setEnabled(true);
        a21.setEnabled(true);
        a22.setEnabled(true);
        a23.setEnabled(true);
        a24.setEnabled(true);
        a25.setEnabled(true);
        a26.setEnabled(true);
        a27.setEnabled(true);
        a28.setEnabled(true);
        a29.setEnabled(true);
        a30.setEnabled(true);
        a31.setEnabled(true);
        a32.setEnabled(true);
        a33.setEnabled(true);
        a34.setEnabled(true);
        a35.setEnabled(true);
        a36.setEnabled(true);
        a37.setEnabled(true);
        a38.setEnabled(true);
        a39.setEnabled(true);
        a40.setEnabled(true);
    }
    private void mini() {
        a25.setVisible(false);
        a26.setVisible(false);
        a27.setVisible(false);
        a28.setVisible(false);
        a29.setVisible(false);
        a30.setVisible(false);
        a31.setVisible(false);
        a32.setVisible(false);
        a33.setVisible(false);
        a34.setVisible(false);
        a35.setVisible(false);
        a36.setVisible(false);
        a37.setVisible(false);
        a38.setVisible(false);
        a39.setVisible(false);
        a40.setVisible(false);
    }

    private void primera() {
        a25.setVisible(true);
        a26.setVisible(true);
        a27.setVisible(true);
        a28.setVisible(true);
        a29.setVisible(true);
        a30.setVisible(true);
        a31.setVisible(true);
        a32.setVisible(true);
        a33.setVisible(true);
        a34.setVisible(true);
        a35.setVisible(true);
        a36.setVisible(true);
        a37.setVisible(true);
        a38.setVisible(true);
        a39.setVisible(true);
        a40.setVisible(true);
    }

    private void lujo() {
        a37.setVisible(false);
        a38.setVisible(false);
        a39.setVisible(false);
        a40.setVisible(false);
    }

    private void AgregarDestino() {
        Object origenc = origen.getSelectedItem();
        ConexionLocal();
        List<Lugares> listLugares;
        listLugares = cl.findLugaresEntities();
        for (int i = 0; i < listLugares.size(); i++) {
            if (listLugares.get(i).getLugar().toString().equals(origenc)) {
                i++;
            } else {
                destino.addItem(listLugares.get(i).getLugar());
            }
           // System.out.println(destino);
        }

    }

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        a6.setEnabled(false);
    }//GEN-LAST:event_a6ActionPerformed

    private void a10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a10ActionPerformed
       a10.setEnabled(false);
    }//GEN-LAST:event_a10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            BuscarC();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void origenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_origenMouseClicked
        destino.removeAllItems();
        AgregarDestino();

    }//GEN-LAST:event_origenMouseClicked

    private void corridasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corridasMouseClicked

    }//GEN-LAST:event_corridasMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = corridas.getSelectedRow();
        if ((int) corridas.getValueAt(i, 7) == 24) {
            mini();
        } else if ((int) corridas.getValueAt(i, 7) == 40) {
            primera();
        } else {
            lujo();
        }
        JOptionPane.showMessageDialog(null, "Has seleccionado una corrida con origen en " + corridas.getValueAt(i, 1).toString() + " y destino en " + corridas.getValueAt(i, 2).toString()
                + "\n" + " programada para la fecha " + corridas.getValueAt(i, 3).toString() + " autobus de clase " + corridas.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        a1.setEnabled(false);
    }//GEN-LAST:event_a1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Activar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
       a2.setEnabled(false);
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        a3.setEnabled(false);
    }//GEN-LAST:event_a3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
       a4.setEnabled(false);
    }//GEN-LAST:event_a4ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        a5.setEnabled(false);
    }//GEN-LAST:event_a5ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
        a7.setEnabled(false);
    }//GEN-LAST:event_a7ActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
       a8.setEnabled(false);
    }//GEN-LAST:event_a8ActionPerformed

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
        a9.setEnabled(false);
    }//GEN-LAST:event_a9ActionPerformed

    private void a11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a11ActionPerformed
        a11.setEnabled(false);
    }//GEN-LAST:event_a11ActionPerformed

    private void a12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a12ActionPerformed
       a12.setEnabled(false);
    }//GEN-LAST:event_a12ActionPerformed

    private void a13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a13ActionPerformed
       a13.setEnabled(false);
    }//GEN-LAST:event_a13ActionPerformed

    private void a14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a14ActionPerformed
        a14.setEnabled(false);
    }//GEN-LAST:event_a14ActionPerformed

    private void a15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a15ActionPerformed
       a15.setEnabled(false);
    }//GEN-LAST:event_a15ActionPerformed

    private void a16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a16ActionPerformed
        a16.setEnabled(false);
    }//GEN-LAST:event_a16ActionPerformed

    private void a17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a17ActionPerformed
      a17.setEnabled(false);
    }//GEN-LAST:event_a17ActionPerformed

    private void a18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a18ActionPerformed
       a18.setEnabled(false);
    }//GEN-LAST:event_a18ActionPerformed

    private void a19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a19ActionPerformed
        a19.setEnabled(false);
    }//GEN-LAST:event_a19ActionPerformed

    private void a20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a20ActionPerformed
       a20.setEnabled(false);
    }//GEN-LAST:event_a20ActionPerformed

    private void a21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a21ActionPerformed
       a21.setEnabled(false);
    }//GEN-LAST:event_a21ActionPerformed

    private void a22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a22ActionPerformed
        a22.setEnabled(false);
    }//GEN-LAST:event_a22ActionPerformed

    private void a23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a23ActionPerformed
        a23.setEnabled(false);
    }//GEN-LAST:event_a23ActionPerformed

    private void a24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a24ActionPerformed
        a24.setEnabled(false);
    }//GEN-LAST:event_a24ActionPerformed

    private void a25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a25ActionPerformed
        a25.setEnabled(false);
    }//GEN-LAST:event_a25ActionPerformed

    private void a26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a26ActionPerformed
        a26.setEnabled(false);
    }//GEN-LAST:event_a26ActionPerformed

    private void a27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a27ActionPerformed
        a27.setEnabled(false);
    }//GEN-LAST:event_a27ActionPerformed

    private void a28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a28ActionPerformed
        a28.setEnabled(false);
    }//GEN-LAST:event_a28ActionPerformed

    private void a29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a29ActionPerformed
        a29.setEnabled(false);
    }//GEN-LAST:event_a29ActionPerformed

    private void a30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a30ActionPerformed
       a30.setEnabled(false);
    }//GEN-LAST:event_a30ActionPerformed

    private void a31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a31ActionPerformed
       a31.setEnabled(false);
    }//GEN-LAST:event_a31ActionPerformed

    private void a32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a32ActionPerformed
        a32.setEnabled(false);
    }//GEN-LAST:event_a32ActionPerformed

    private void a33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a33ActionPerformed
      a33.setEnabled(false);
    }//GEN-LAST:event_a33ActionPerformed

    private void a34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a34ActionPerformed
        a34.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_a34ActionPerformed

    private void a35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a35ActionPerformed
        a35.setEnabled(false);
    }//GEN-LAST:event_a35ActionPerformed

    private void a36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a36ActionPerformed
        a36.setEnabled(false);
    }//GEN-LAST:event_a36ActionPerformed

    private void a37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a37ActionPerformed
        a37.setEnabled(false);
    }//GEN-LAST:event_a37ActionPerformed

    private void a38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a38ActionPerformed
        a38.setEnabled(false);
    }//GEN-LAST:event_a38ActionPerformed

    private void a39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a39ActionPerformed
        a39.setEnabled(false);
    }//GEN-LAST:event_a39ActionPerformed

    private void a40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a40ActionPerformed
      a40.setEnabled(false);
    }//GEN-LAST:event_a40ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AutobusesPUEntityManager0;
    private javax.swing.JButton a1;
    private javax.swing.JButton a10;
    private javax.swing.JButton a11;
    private javax.swing.JButton a12;
    private javax.swing.JButton a13;
    private javax.swing.JButton a14;
    private javax.swing.JButton a15;
    private javax.swing.JButton a16;
    private javax.swing.JButton a17;
    private javax.swing.JButton a18;
    private javax.swing.JButton a19;
    private javax.swing.JButton a2;
    private javax.swing.JButton a20;
    private javax.swing.JButton a21;
    private javax.swing.JButton a22;
    private javax.swing.JButton a23;
    private javax.swing.JButton a24;
    private javax.swing.JButton a25;
    private javax.swing.JButton a26;
    private javax.swing.JButton a27;
    private javax.swing.JButton a28;
    private javax.swing.JButton a29;
    private javax.swing.JButton a3;
    private javax.swing.JButton a30;
    private javax.swing.JButton a31;
    private javax.swing.JButton a32;
    private javax.swing.JButton a33;
    private javax.swing.JButton a34;
    private javax.swing.JButton a35;
    private javax.swing.JButton a36;
    private javax.swing.JButton a37;
    private javax.swing.JButton a38;
    private javax.swing.JButton a39;
    private javax.swing.JButton a4;
    private javax.swing.JButton a40;
    private javax.swing.JButton a5;
    private javax.swing.JButton a6;
    private javax.swing.JButton a7;
    private javax.swing.JButton a8;
    private javax.swing.JButton a9;
    private com.toedter.calendar.JDateChooser calendario1;
    private javax.swing.JTable corridas;
    private java.util.List<modelo.Corridas> corridasList;
    private java.util.List<modelo.Corridas> corridasList1;
    private java.util.List<modelo.Corridas> corridasList2;
    private javax.persistence.Query corridasQuery;
    private javax.persistence.Query corridasQuery1;
    private javax.persistence.Query corridasQuery2;
    private javax.swing.JComboBox destino;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox origen;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
